concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: setup pnpm
        uses: pnpm/setup@v1
      - name: run `pnpm run check:fmt`
        run: pnpm run check:fmt
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: setup pnpm
        uses: pnpm/setup@v1
      - name: run `pnpm run check:lint`
        run: pnpm run check:lint
  types:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: setup pnpm
        uses: pnpm/setup@v1
      - name: run `pnpm run check:types`
        run: pnpm run check:types
name: ci
on:
  pull_request:
  push:
    branches:
      - master
